apiVersion: v1
kind: Service
metadata:
  name: cicd-app-svc
  labels: 
    app: cicd-app
spec:
  selector:
    app: cicd-app
  type: ClusterIP
  ports:
  - name: app
    protocol: TCP
    port: 88
    targetPort: 8080